### ISSUE TITLE
Lekce 1

### ISSUE THREAD

**Issue by pesikj** [pesikj/python-012021-sample#1]
* U úkolu 1 řešíš pouze situaci, že balík doručen byl, ale neřešíš situaci, že nebyl.
* Úkol 2 je v pořádku.
* Úkol 3 je v pořádku.

**Comment by pesikj** [comment]
@pesikj Opraveno.

**Comment by pesikj** [comment]
Úkol 1 je v pořádku.

**Comment by andywaltlova** [comment]
1. úkol máš moc krásnej :-) (Ale teda v [teto](https://youtu.be/hgI0p1zf31k) pisnicce zpivaji ze do pythonu camelCase nepatri)

**Comment by pesikj** [comment]
@andywaltlova Moc děkuji za komentář :-)
